# Generated by Django 6.0.4 on 2026-04-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
    ]
